boardswarm/boardswarm

boardswarm/src/main.rs
boardswarm/src/serial/mod.rs

Detect getting an EOF from a serial device (e.g. due to unplug) and bail out of the read loop at that point.

Fix serial looping on disconnect

---

boardswarm-client/src/client.rs

The maximum decode size of gRPC is 4 megabytes by default, limit the maximum write requests to 3 megabyte to stay nicely within that limit.

boardswarm-client: Limit maximum write size to 3Mb

---

boardswarm/README.md
boardswarm/share/server.conf

I have corrected a bunch of apparent typing mistakes. A native speaker would be welcome to verify what I did. While at it, I added links to OIDC and JWT definitions.

Fix a bunch of typos and add some links to definitions

---

boardswarm/src/dfu.rs
boardswarm/src/gpio.rs
boardswarm/src/pdudaemon.rs
boardswarm/src/rockusb.rs
boardswarm/src/serial/mod.rs

gpio: Print debug information about unmatched devices
It can be helpful to understand why a gpio device wasn't registered. Rework
the registration code to check if it matches against the required device
earlier, then print the device's name and properties if the matching
fails e.g:
DEBUG boardswarm::gpio: Ignoring gpio device /sys/devices/platform/AMDI0030:00/gpiochip0 - Properties { properties: {"udev.DEVNAME": "/dev/gpiochip0", ... }

gpio: Print debug information about unmatched devices & add tracing instrumentation to start_provider

---

Cargo.lock
boardswarm-cli/Cargo.toml
boardswarm-cli/src/main.rs

"properties" is a hash map so there's no guaranteed order while iterating over it. From cli user's perspective this is confusing, because properties of the same item will be listed in random order each time this command is run.
Sort the output, using itertools.

Sort output of "properties" command

---

boardswarm-cli/src/main.rs

Example session:
```
$ target/debug/boardswarm-cli -i my-boardswarm configure \
--new --uri http://localhost:6683
thread 'main' panicked at boardswarm-cli/src/main.rs:538:34:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
is a result of not providing a JWT token, in which case OIDC is silently attempted.
This pull request does 2 things:
1) informs the user about which authentication method is being chosen, which makes the user aware that e.g. the actually
chosen method is OIDC even though the user might have thought otherwise
2) ensures that "unwrap()" is not called on a None variant, providing a meaningful message to the user instead of panic!()

Better inform about authentication

---

boardswarm-cli/README.md

This should've gone with the changes refactoring "configure" into "auth".

cli: Update the README to use 'auth' instead of 'configure'

---

boardswarm-cli/src/main.rs

download-boot is missing its help text.

cli: Add help entry to "donwload-boot" rock command

---

boardswarm/README.md
boardswarm/share/99-boardswarm.rules
boardswarm/share/boardswarm.service

Add an example systemd service file to the share directory.

boardswarm: Add example systemd service & udev rules

---

boardswarm/src/pdudaemon.rs

Currently boardswarm panics if pdudaemon returns an error. Make it a little more gracious and bubble up an error instead.
This is not currently a problem, since pdudaemon will not return errors until https://github.com/pdudaemon/pdudaemon/pull/158 is merged.
Fixes: boardswarm/boardswarm#81

Graciously handle pdudaemon errors

---

boardswarm/src/gpio.rs
boardswarm/src/main.rs
boardswarm/src/registry.rs

If the `match` configuration is empty, we are (by-design) quite greedy and match any subdevice. Warn the user about that situation.

Warn when match configuration is empty

---

.github/workflows/ci.yml

Only push images to ghrc on push events to the repository rather then on anything that's not a pull request. Also only push from the main branch to main packages, from other branches push to a package with a `-ci` suffix to they're clearly seperated

Minimize images stored in ghcr

---

.github/workflows/dist-notes.md
.github/workflows/dist.yml
Cargo.lock
boardswarm-cli/Dockerfile
boardswarm-client/Cargo.toml
boardswarm-protocol/Cargo.toml
boardswarm-protocol/build.rs
boardswarm/Cargo.toml
boardswarm/Dockerfile
deny.toml

Both ring and openssl ended up being used in boardswarm; standardize on ring to avoid requiring a specific openssl library on the host.

Avoid linking against openssl

---

boardswarm-cli/src/main.rs

For most commands logging to stdout/stderr makes total sense; When doing Ui it does not, so don't initial the fmt subscriber in that case

cli: Don't log to stdout when running the ui

---

boardswarm-cli/src/main.rs
boardswarm-client/src/client.rs
boardswarm-client/src/device.rs
boardswarm-protocol/proto/boardswarm.proto
boardswarm/src/boardswarm_provider/volume.rs
boardswarm/src/dfu.rs
boardswarm/src/fastboot.rs
boardswarm/src/main.rs
boardswarm/src/mediatek_brom.rs
boardswarm/src/rockusb.rs

As not all volume protocols support discovering all valid targets, allow the user to specify targets names outside of the target list.

Support dynamic targets

---

boardswarm-cli/src/main.rs
boardswarm-client/src/client.rs
boardswarm-client/src/device.rs
boardswarm-protocol/proto/boardswarm.proto
boardswarm/src/fastboot.rs
boardswarm/src/main.rs

Some protocols allow erasing volumes (e.g. discard in case of flash). Add support for that in the protocol, cli and the fastboot volume provider

Add protocol/API/cli to erase volume targets

---

boardswarm/src/mediatek_brom.rs

This merge request fixes a possible panic that I encountered while I was testing #161 on a Genio 1200 board:
```
Running `target/debug/boardswarm /home/laeyraud/Dev/boardswarm_cfg/server.conf`
thread 'tokio-runtime-worker' panicked at boardswarm/src/mediatek_brom.rs:79:62:
called `Result::unwrap()` on an `Err` value: Brom(IncorrectHandshakeResponse)
```
I still don't know the conditions to make it trigger but better fix it anyway as it's an easy fix.

Fix panics during mediatek brom volume setup

---

boardswarm/src/dfu.rs
boardswarm/src/mediatek_brom.rs
boardswarm/src/rockusb.rs

Some USB products may set ID_MODEL to its own custom string but if its not set then udev sets ID_MODEL to ID_MODEL_ID (e.g. the idProduct, the actual device's PID).
Both properties are set by udev's usb builtin - except in the cases where ID_MODEL is set by the USB device to a custom string. The _ID variants directly come from idVendor and idProduct (e.g. the actual VID and PID), while the bare ID_VENDOR and ID_MODEL variants first try to use manufacturer and product instead (e.g. the optional Manufacturer and Product strings provided by the USB device) when a fallback to the VID/PID.
Rework the code to use the _ID variants where device IDs are used. This causes no functional change.
Fixes: https://github.com/boardswarm/boardswarm/issues/160

Use ID_MODEL_ID instead of ID_MODEL for USB devices

---

boardswarm-cli/src/main.rs

When passing non-JSON to `boardswarm-cli actuator change-mode`, boardswarm-cli shows a slightly obscure error message which doesn't explain that the error is caused by JSON decode:
```
Error: expected value at line 1 column 1
```
Add context to the error message so that the error is a little more helpful the cause:
```
Error: Failed to parse actuator command as JSON
Caused by:
expected value at line 1 column 1
```
Also apply the same fix to the console command deserialisation.
Fixes: https://github.com/boardswarm/boardswarm/issues/165

boardswarm-cli: Add context to JSON deserialisation

---

Cargo.lock
boardswarm-cli/Cargo.toml
boardswarm-cli/src/main.rs

Issue: https://github.com/boardswarm/boardswarm/issues/38
Follow up of: https://github.com/boardswarm/boardswarm/pull/172
As done for the write-aimg command, add a status bar to write-bmap showing the current progress on the number of mapped bytes writen.

cli: Add progress bar to write-bmap command

---

Cargo.lock
boardswarm-cli/Cargo.toml
boardswarm-cli/src/main.rs
boardswarm-cli/src/ui.rs

This merge requests aims to improve the terminal ergonomics in UI mode (see #87).
Previously, the console terminal size  was hardcoded to 80 characters x 24 lines. Now the UI size is auto detected and resized on the fly to fit the main terminal. 
A new option "--scrollback-lines" is also added to manually configure the scrollback buffer.

Increase UI terminal size

---

boardswarm/src/fastboot.rs

In the case the fastboot env value max-download-size is read but failed to parse, let's report the bad value.

boardswarm: fastboot: Log max-download-size var value on error

---

.github/workflows/ci.yml
Cargo.lock
boardswarm-cli/Cargo.toml
boardswarm-client/Cargo.toml
boardswarm-protocol/Cargo.toml
boardswarm/Cargo.toml

0.3 adds robustness for arguably broken fastboot implementation sending message with trailing garbage bytes after a \0. Required for interacting with the spacemit K1 bootrom fastboot implementation.

Update to fastboot-protocol 0.3

---

Cargo.lock
boardswarm-cli/Cargo.toml
boardswarm-client/Cargo.toml
boardswarm-client/src/authenticator.rs
boardswarm-protocol/Cargo.toml
boardswarm/Cargo.toml
boardswarm/src/main.rs

Test bump to tonic 0.13 and axum 0.8 - Draft (apart from messy commits) as jwt-authorizer needs an update to tonic 0.13 first.. ideally

Tonic 0.13: 

---

boardswarm/src/boardswarm_provider/device.rs
boardswarm/src/boardswarm_provider/mod.rs
boardswarm/src/config_device.rs
boardswarm/src/fastboot.rs
boardswarm/src/gpio.rs
boardswarm/src/main.rs
boardswarm/src/mediatek_brom.rs
boardswarm/src/registry.rs
boardswarm/src/udev.rs

the registration helper was rather limited; Only volume's could be registered with it and at most one of those. Extend that so it can be used for any type as well as supporting multiple items to be registered in a batch
This also refactors the registry indexing so they can be typed rather then just u64, which makes it very explicit what an id refers to.

Improve udev registration helper

---

Cargo.lock
boardswarm/Cargo.toml
boardswarm/src/eswin_eic7700_storage.rs
boardswarm/src/main.rs

```
boardswarm: Add eswin-eic7700-storage provider
The eswin-eic7700-storage provider registers a volume with a single
target `bootloader`.
When in USB download mode, the ESWIN EIC7700X will register itself as a
mass storage device. When the `bootloader_ddr5_secboot.bin` bootloader
artifact is written to its filesystem, it will automatically unregister
and bootstrap into this bootloader image.
Writing to the volume target `bootloader` will create and write the
content to this file `bootloader_ddr5_secboot.bin`.
Example server configuration (HiFive Premier P550 Development Board):
```
providers:
- name: eswin-eic7700-storage
provider: eswin-eic7700-storage
parameters:
match:
udev.ID_VENDOR: "ESWIN"
udev.ID_MODEL: "WIN-2030"
mountpoint: "/var/run/boardswarm/eswin-eic7700-storage"
devices:
- …

boardswarm: Add hifive-p550-storage provider

---

.github/workflows/website.yml
website/Makefile
website/conf.py
website/guides/basic-functionality.rst
website/guides/setup-client.rst
website/guides/setup-server.rst
website/index.rst

First draft of Boardswarm website. covering where to find the code, pointers to existing configuration documentation and a very short users guide.

Add draft of Boardswarm website

---

.github/workflows/website.yml

peaceiris/actions-gh-pages@v3 seems to want to push to a github branch and publish from that. Use the official actions instead to publish an artifact and deploy that on github pages, without the need for a branch

Use official actions for pages

---

boardswarm-cli/src/main.rs

As done for the write-aimg/bmap commands, add a status bar to write() showing the current progress on the number of bytes writen.
Link: https://github.com/boardswarm/boardswarm/issues/38

cli: Add progress bar to device/volume write commands

---

boardswarm-cli/src/main.rs

In the recently added device info output, the volumes are not equally aligned. Those not available should be aligned as the others. Fix this.
```
$ boardswarm-cli -i sjic device sifive-hifive-p550-evk-cbg-0 info
Current mode: download
Modes:
- off
- on (depends on off)
- download (depends on off)
Consoles:
- main - id: 241
Volumes:
* fastboot - not available
- storage - id: 53, targets:
+ bootloader (writable, seekable)
```

boardswarm-cli: Fix misaligned volumes in device info

---

boardswarm/README.md

Commit 646c456 fixed the authentication setup steps in boardswarm-cli/README.md but left out the duplicated commands in boardswarm/README.md.
Fix them as well to use 'auth' instead of 'configure'.
Fixes: 646c456 ("cli: Update the README to use 'auth' instead of 'configure'")
Note: Alternatively, we could describe the client-side authentication step only in boardswarm-cli/README.md and point to that section from boardswarm/README.md. Pro: delete redundancy that lead to this inconsistency. Con: need to jump from one document to the other, as usually you would set up the server and immediately test it with the client. Let me know what you prefer.

boardswarm: README: use 'auth' instead of 'configure'
